name: Install LXD runtime dependencies
description: Installs LXD runtime dependencies

runs:
  using: composite
  steps:
    - name: Installs LXD runtime dependencies
      shell: bash
      run: |
        set -eux
        sudo add-apt-repository ppa:ubuntu-lxc/daily -y --no-update
        sudo apt-get update

        # mask services from lxc-utils (`lxc-*` tools are used in test/suites/lxc-to-lxd.sh)
        # doing this masking before the package is installed means they won't even start
        sudo systemctl mask lxc.service lxc-net.service

        sudo apt-get install --no-install-recommends -y \
          curl \
          git \
          make \
          acl \
          attr \
          bind9-dnsutils \
          btrfs-progs \
          busybox-static \
          dnsmasq-base \
          easy-rsa \
          gettext \
          jq \
          lxc-utils \
          lvm2 \
          nftables \
          quota \
          rsync \
          s3cmd \
          socat \
          sqlite3 \
          squashfs-tools \
          swtpm \
          tar \
          tcl \
          thin-provisioning-tools \
          uuid-runtime \
          xfsprogs \
          xz-utils \
          zfsutils-linux \
          openvswitch-switch

        sudo snap install yq

        # reclaim some space
        sudo apt-get clean
