name: Install Trivy
description: Installs Trivy from deb package

runs:
  using: composite
  steps:
    # We are using the deb package instead of the trivy action because we need to point to the cache directory
    # with cache-dir, and there is currently a bug in that functionality on the Trivy GitHub action.
    # See https://github.com/aquasecurity/trivy-action/issues/12.
    - name: Install Trivy
      shell: bash
      run: |
        mkdir -p /home/runner/vuln-cache
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
