API:
- changed-files:
  - any-glob-to-any-file:
    - doc/api-extensions.md
    - doc/rest-api.yaml
    - shared/api/**/*
Documentation:
- changed-files:
  - any-glob-to-any-file:
    - doc/**/*

"5.21 LTS":
- base-branch: 'stable-5.21'

"5.0 LTS":
- base-branch: 'stable-5.0'

"4.0 LTS":
- base-branch: 'stable-4.0'
