name: Setup MicroOVN
description: |
  Setup MicroOVN snap. Once bootstrapped, the MicroOVN CA certificate is located
  at `/var/snap/microovn/common/data/pki/cacert.pem`.

  To configure LXD to use it:

  ```
  lxc config set network.ovn.northbound_connection "ssl:127.0.0.1:6641"
  ```

inputs:
  microovn-channel:
    description: MicroOVN snap channel to install
    default: "latest/edge"
    type: string

runs:
  using: composite
  steps:
    - name: Install MicroOVN snap
      shell: bash
      run: |
          set -eux
          # External repos using this action won't have access to the `test/includes/snap.sh` file
          # so install directly from the store instead.
          if [ -e test/includes/snap.sh ]; then
            sudo bash -c ". test/includes/snap.sh; install_snap microovn ${{ inputs.microovn-channel }}"
          else
            sudo snap install microovn --channel "${{ inputs.microovn-channel }}"
          fi

    - name: Configure MicroOVN snap
      shell: bash
      run: |
          set -eux

          sudo microovn waitready
          sudo microovn cluster bootstrap
          sudo microovn status
