#!/bin/bash
set -eux

# Install dependencies
install_deps jq

# Install LXD
install_lxd

# Configure LXD
lxc network create lxdbr0
lxc profile device add default eth0 nic network=lxdbr0

IMAGE="${TEST_IMG:-ubuntu-minimal-daily:26.04}"

poolName="vmpool$$"
poolDriver=dir

echo "==> Create storage pool using driver ${poolDriver}"
lxc storage create "${poolName}" "${poolDriver}"

echo "==> Create VM and boot"
if hasNeededAPIExtension devlxd_images_vm; then
  lxc launch "${IMAGE}" v1 --vm -s "${poolName}" -c security.devlxd.images=true
else
  lxc launch "${IMAGE}" v1 --vm -s "${poolName}"
fi

waitInstanceBooted v1 # Need ready for go coverage and networking for apt-get below
setup_instance_gocoverage v1
lxc info v1

echo "==> Checking devlxd is working"

lxc exec v1 -- apt-get update
lxc exec v1 -- apt-get install --no-install-recommends --yes curl

# devlxd is enabled by default and should work
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'instance-id:'
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'local-hostname:'

# Run sync before forcefully restarting the VM otherwise the filesystem will be corrupted.
lxc exec v1 -- sync
prepare_vm_for_hard_stop v1
lxc restart -f v1
waitInstanceReady v1

# devlxd should be running after restart
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'instance-id:'
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'local-hostname:'

# Disable devlxd
lxc config set v1 security.devlxd false

echo "==> Checking devlxd is not working"

! lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 || false

lxc exec v1 -- sync
prepare_vm_for_hard_stop v1
lxc restart -f v1
waitInstanceReady v1

# devlxd should not be running after restart
! lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 || false

echo "==> Checking devlxd can be enabled live"

# Enable devlxd
lxc config set v1 security.devlxd true

# devlxd should be running after the config is enabled
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq

# Ensure that the outputed metadata is in correct format.
META_DATA="$(lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data)"
grep -xE 'instance-id: [^ ]{36}' <<< "${META_DATA}"
grep -xF 'local-hostname: v1' <<< "${META_DATA}"

# Test cloud-init user-data.
# Ensure the header is preserved and the outputed value is not escaped.
cloudInitUserData="#cloud-config
package_update: false
package_upgrade: false
runcmd:
- echo test"

lxc config set v1 cloud-init.user-data "${cloudInitUserData}"
out=$(lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock lxd/1.0/config/cloud-init.user-data)
[ "${out}" = "${cloudInitUserData}" ]
lxc config unset v1 cloud-init.user-data

if hasNeededAPIExtension instance_ready_state; then
  # test instance Ready state
  lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Ready"}' http://custom.socket/1.0
  [ "$(lxc config get v1 volatile.last_state.ready)" = "true" ]

  lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Started"}' http://custom.socket/1.0
  [ "$(lxc config get v1 volatile.last_state.ready)" = "false" ]

  lxc exec v1 -- curl -s --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Ready"}' http://custom.socket/1.0
  [ "$(lxc config get v1 volatile.last_state.ready)" = "true" ]
  prepare_vm_for_hard_stop v1
  lxc stop -f v1
  sleep 5
  [ "$(lxc config get v1 volatile.last_state.ready)" = "false" ]

  lxc start v1
else
  echo "Skipping instance Ready state tests, not supported"
fi

# Wait for boot to be completed to interact with snap/snapd
waitInstanceBooted v1

# Test nested VM functionality.
lxc exec v1 -- sh -c "$(declare -f waitSnapdSeed); waitSnapdSeed"
lxc exec v1 -- snap install lxd --channel="${LXD_SNAP_CHANNEL}" --cohort=+
lxc exec v1 -- lxd init --auto
if [ -n "${LXD_SIDELOAD_PATH:-}" ]; then
    lxc file push "${LXD_SIDELOAD_PATH}" v1/var/snap/lxd/common/lxd.debug
    lxc exec v1 -- systemctl restart snap.lxd.daemon
fi
if [ -n "${LXD_AGENT_SIDELOAD_PATH:-}" ]; then
  lxc file push "${LXD_AGENT_SIDELOAD_PATH}" "v1/root/$(basename "${LXD_AGENT_SIDELOAD_PATH}")"
  lxc exec v1 -- mount --bind "$(basename "${LXD_AGENT_SIDELOAD_PATH}")" /snap/lxd/current/bin/lxd-agent
  lxc exec v1 -- systemctl restart snap.lxd.daemon
fi

monitorPID=""
if hasNeededAPIExtension devlxd_images_vm; then
  lxc monitor --type lifecycle --format json > monitor.json 2>&1 &
  monitorPID="${!}"
fi

lxc exec v1 -- /snap/bin/lxc launch "${IMAGE}" v1v1 --vm
sleep 30
lxc exec v1 -- /snap/bin/lxc info v1v1 | grep -F RUNNING

if hasNeededAPIExtension devlxd_images_vm; then
  kill "${monitorPID}"

  # If the guest retrieved the image from the host, the host should emit an "image-retrieved" lifecycle event. The
  # requestor address tells us that this was definitely the guest.
  # Newer LXD versions use the protocol instead of the requestor address to distinguish devlxd requests
  grep -wF 'image-retrieved' monitor.json | jq --exit-status '.metadata.requestor | (.address == "@devlxd" or .protocol == "devlxd")'
  rm monitor.json
fi

echo "==> Deleting VM"
prepare_vm_for_hard_stop v1
lxc delete -f v1
lxc profile device remove default eth0

echo "==> Deleting storage pool"
lxc storage delete "${poolName}"

echo "==> Deleting storage pool"
lxc network delete lxdbr0

# shellcheck disable=SC2034
FAIL=0
