#!/bin/bash
set -eux

# Install dependencies
install_deps jq

# Install LXD
install_lxd

# Configure LXD
lxc network create lxdbr0
lxc profile device add default eth0 nic network=lxdbr0

IMAGE="${TEST_IMG:-ubuntu-minimal-daily:26.04}"

poolName="ctpool$$"
poolDriver=dir

echo "==> Create storage pool using driver ${poolDriver}"
lxc storage create "${poolName}" "${poolDriver}"

echo "==> Create container and boot"
lxc launch "${IMAGE}" c1 -s "${poolName}" -c security.nesting=true
lxc info c1

echo "==> Checking devlxd is working"
waitInstanceBooted c1 # Need networking for apt-get
lxc exec c1 -- apt-get update
lxc exec c1 -- apt-get install --no-install-recommends --yes curl

# devlxd is enabled by default and should work
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
if hasNeededAPIExtension cloud_init; then
  lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
fi
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -Fq 'instance-id:'
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -Fq 'local-hostname: c1'

# Check devlxd instance name validation works (5.21 onwards).
if ! echo "${LXD_SNAP_CHANNEL}" | grep -qE "^[45]\.0/"; then
  lxc launch "${IMAGE}" c2 -s "${poolName}"

  # First check first discovery method (where curl process isn't under the lxc monitor process tree).
  # Explanation of command:
  # Running `bash -c "exec -a '[lxc monitor]' sleep 100"` results in a process name of "[lxc monitor] 100".
  # LXD looks for the project name and instance name at the end of the process name in the format " <project_name>_<instance_name>".
  # So use the curl `--proxy` option to allow adding " <project_name>_<instance_name>" to the end of the process name.
  # This works because `--proxy` is not used in combination with `--unix-socket`.
  lxc exec c1 -- bash -c "exec -a '[lxc monitor]' curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data --proxy ' default_c2'" | grep -Fq 'local-hostname: c1'
  lxc exec c1 -- bash -c "exec -a '[lxc monitor]' curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data --proxy ' default_missing'" | grep -Fq 'local-hostname: c1'
  lxc exec c1 -- bash -c "exec -a '[lxc monitor]' curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data --proxy ' missing_missing'" | grep -Fq 'local-hostname: c1'

  # Next check the second discovery method (where the curl process is under the lxc monitor process tree).
  # systemd-run requires D-Bus, so wait until c1 is fully booted before proceeding.
  waitInstanceBooted c1
  lxc exec c1 -- systemd-run --pipe --wait --quiet bash -c "exec -a '[lxc monitor]' curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data --proxy ' default_c2'" | grep -Fq 'local-hostname: c1'
  lxc exec c1 -- systemd-run --pipe --wait --quiet bash -c "exec -a '[lxc monitor]' curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data --proxy ' default_missing'" | grep -Fq 'local-hostname: c1'
  lxc exec c1 -- systemd-run --pipe --wait --quiet bash -c "exec -a '[lxc monitor]' curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data --proxy ' missing_missing'" | grep -Fq 'local-hostname: c1'

  lxc delete -f c2
fi

# Restart the container
lxc restart -f c1

# devlxd should be running after restart
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
if hasNeededAPIExtension cloud_init; then
  lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
fi
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -Fq 'instance-id:'
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -Fq 'local-hostname: c1'

# Disable devlxd
lxc config set c1 security.devlxd false

echo "==> Checking devlxd is not working"

! lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0 || false

lxc restart -f c1

# devlxd should not be running after restart
! lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0 || false

echo "==> Checking devlxd can be enabled live"

# Enable devlxd
lxc config set c1 security.devlxd true
lxc config set c1 security.devlxd.images true

# devlxd should be running after the config is enabled
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
if hasNeededAPIExtension cloud_init; then
  lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
fi
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -Fq 'instance-id:'
lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -Fq 'local-hostname: c1'

if hasNeededAPIExtension instance_ready_state; then
  # test instance Ready state
  lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Ready"}' http://custom.socket/1.0
  [ "$(lxc config get c1 volatile.last_state.ready)" = "true" ]

  lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Started"}' http://custom.socket/1.0
  [ "$(lxc config get c1 volatile.last_state.ready)" = "false" ]

  lxc exec c1 -- curl --silent --show-error --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Ready"}' http://custom.socket/1.0
  [ "$(lxc config get c1 volatile.last_state.ready)" = "true" ]
  lxc stop -f c1
  sleep 5
  [ "$(lxc config get c1 volatile.last_state.ready)" = "false" ]

  lxc start c1
  waitInstanceBooted c1
else
  echo "Skipping instance Ready state tests, not supported"
fi

# Below tests for image export rely on an event being emitted on export. This will not be backported to 4.0 or 5.0,
# so exit the test here.
if echo "${LXD_SNAP_CHANNEL}" | grep -E '^([45]\.0)/'; then
  echo "Skipping devlxd image export tests, not supported"
  FAIL=0
  exit
fi

# We need snapd to be ready before the next tests.
lxc exec c1 -- sh -c "$(declare -f waitSnapdSeed); waitSnapdSeed"
lxc exec c1 -- snap install lxd --channel="${LXD_SNAP_CHANNEL}" --cohort=+
lxc exec c1 -- lxd init --auto

lxc monitor --type lifecycle --format json > monitor.json 2>&1 &
monitorPID="${!}"

# Launch an image we know is on the host.
lxc exec c1 -- /snap/bin/lxc launch "${IMAGE}" c1c1
lxc exec c1 -- /snap/bin/lxc info c1c1 | grep -F RUNNING

kill "${monitorPID}"

# If the guest retrieved the image from the host, the host should emit an "image-retrieved" lifecycle event. The
# requestor address tells us that this was definitely the guest.
# Newer LXD versions use the protocol instead of the requestor address to distinguish devlxd requests
grep -wF 'image-retrieved' monitor.json | jq --exit-status '.metadata.requestor | (.address == "@devlxd" or .protocol == "devlxd")'
rm monitor.json

echo "==> Deleting container"
lxc delete -f c1
lxc profile device remove default eth0

echo "==> Deleting storage pool"
lxc storage delete "${poolName}"

echo "==> Deleting storage pool"
lxc network delete lxdbr0

# shellcheck disable=SC2034
FAIL=0
