// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovsmodel

const InterfaceTable = "Interface"

type (
	InterfaceAdminState       = string
	InterfaceCFMRemoteOpstate = string
	InterfaceDuplex           = string
	InterfaceLinkState        = string
)

var (
	InterfaceAdminStateUp         InterfaceAdminState       = "up"
	InterfaceAdminStateDown       InterfaceAdminState       = "down"
	InterfaceCFMRemoteOpstateUp   InterfaceCFMRemoteOpstate = "up"
	InterfaceCFMRemoteOpstateDown InterfaceCFMRemoteOpstate = "down"
	InterfaceDuplexHalf           InterfaceDuplex           = "half"
	InterfaceDuplexFull           InterfaceDuplex           = "full"
	InterfaceLinkStateUp          InterfaceLinkState        = "up"
	InterfaceLinkStateDown        InterfaceLinkState        = "down"
)

// Interface defines an object in Interface table
type Interface struct {
	UUID                 string                     `ovsdb:"_uuid"`
	AdminState           *InterfaceAdminState       `ovsdb:"admin_state"`
	BFD                  map[string]string          `ovsdb:"bfd"`
	BFDStatus            map[string]string          `ovsdb:"bfd_status"`
	CFMFault             *bool                      `ovsdb:"cfm_fault"`
	CFMFaultStatus       []string                   `ovsdb:"cfm_fault_status"`
	CFMFlapCount         *int                       `ovsdb:"cfm_flap_count"`
	CFMHealth            *int                       `ovsdb:"cfm_health"`
	CFMMpid              *int                       `ovsdb:"cfm_mpid"`
	CFMRemoteMpids       []int                      `ovsdb:"cfm_remote_mpids"`
	CFMRemoteOpstate     *InterfaceCFMRemoteOpstate `ovsdb:"cfm_remote_opstate"`
	Duplex               *InterfaceDuplex           `ovsdb:"duplex"`
	Error                *string                    `ovsdb:"error"`
	ExternalIDs          map[string]string          `ovsdb:"external_ids"`
	Ifindex              *int                       `ovsdb:"ifindex"`
	IngressPolicingBurst int                        `ovsdb:"ingress_policing_burst"`
	IngressPolicingRate  int                        `ovsdb:"ingress_policing_rate"`
	LACPCurrent          *bool                      `ovsdb:"lacp_current"`
	LinkResets           *int                       `ovsdb:"link_resets"`
	LinkSpeed            *int                       `ovsdb:"link_speed"`
	LinkState            *InterfaceLinkState        `ovsdb:"link_state"`
	LLDP                 map[string]string          `ovsdb:"lldp"`
	MAC                  *string                    `ovsdb:"mac"`
	MACInUse             *string                    `ovsdb:"mac_in_use"`
	MTU                  *int                       `ovsdb:"mtu"`
	MTURequest           *int                       `ovsdb:"mtu_request"`
	Name                 string                     `ovsdb:"name"`
	Ofport               *int                       `ovsdb:"ofport"`
	OfportRequest        *int                       `ovsdb:"ofport_request"`
	Options              map[string]string          `ovsdb:"options"`
	OtherConfig          map[string]string          `ovsdb:"other_config"`
	Statistics           map[string]int             `ovsdb:"statistics"`
	Status               map[string]string          `ovsdb:"status"`
	Type                 string                     `ovsdb:"type"`
}
