name: Setup MicroCeph
description: Setup MicroCeph to use the ephemeral disk of GHA runners

inputs:
  microceph-channel:
    description: MicroCeph snap channel to install
    default: "latest/edge"
    required: false
  osd-count:
    description: Number of OSDs to add to MicroCeph
    default: "1"
    required: false
  snap-cache-dir:
    description: Directory to use for snap cache
    default: "/home/runner/snap-cache"
    required: false

runs:
  using: composite
  steps:
    - name: Ephemeral disk checks
      shell: bash
      run: |
          set -eux

          # If the rootfs and the ephemeral part are on the same physical disk, giving the whole
          # disk to microceph would wipe our rootfs. Since it is pretty rare for GitHub Action
          # runners to have a single disk, we immediately bail rather than trying to gracefully
          # handle it. Once snapd releases with https://github.com/snapcore/snapd/pull/13150,
          # we will be able to stop worrying about that special case.
          if [ "$(stat -c '%d' /)" = "$(stat -c '%d' /mnt)" ]; then
            echo "FAIL: rootfs and ephemeral part on the same disk, aborting"
            exit 1
          fi

    - name: Free-up ephemeral disk
      shell: bash
      id: free_ephemeral_disk
      run: |
          set -eux

          # Avoid LXD snap holding on to swap (https://github.com/canonical/lxd/issues/14768)
          sudo snap remove --purge lxd || true

          sudo swapoff /mnt/swapfile
          ephemeral_disk="$(findmnt --noheadings --output SOURCE --target /mnt | sed 's/[0-9]\+$//')"
          sudo umount /mnt
          echo "ephemeral_disk=${ephemeral_disk}" >> "${GITHUB_OUTPUT}"

    - name: Install MicroCeph snap
      shell: bash
      env:
        SNAP_CACHE_DIR: ${{ inputs.snap-cache-dir }}
        SNAP_CHANNEL: ${{ inputs.microceph-channel }}
      run: |
          set -eux
          # External repos using this action won't have access to the `test/includes/snap.sh` file
          # so install directly from the store instead.
          if [ -e test/includes/snap.sh ]; then
            sudo --preserve-env=SNAP_CACHE_DIR bash -c "
              . test/includes/snap.sh; \
              install_snap snapd latest/beta; \
              install_snap core24 latest/stable; \
              install_snap microceph \"${SNAP_CHANNEL}\"; \
            "
          else
            sudo snap install microceph --channel="${SNAP_CHANNEL}"
          fi

    - name: Configure MicroCeph snap
      shell: bash
      env:
        STEPS_FREE_EPHEMERAL_DISK_OUTPUTS_EPHEMERAL_DISK: ${{ steps.free_ephemeral_disk.outputs.ephemeral_disk }}
        INPUTS_OSD_COUNT: ${{ inputs.osd-count }}
      run: |
          set -eux

          cleanup() {
            set +e
            # dmesg may contain oops, IO errors, crashes, etc
            echo "::group::dmesg logs"
            journalctl --quiet --no-hostname --no-pager --boot=0 --lines=100 --dmesg
            echo "::endgroup::"
            exit 1
          }
          trap cleanup ERR HUP INT TERM

          ephemeral_disk="${STEPS_FREE_EPHEMERAL_DISK_OUTPUTS_EPHEMERAL_DISK}"
          sudo microceph cluster bootstrap
          sudo microceph.ceph config set global mon_allow_pool_size_one true
          sudo microceph.ceph config set global mon_allow_pool_delete true
          sudo microceph.ceph config set global osd_pool_default_size 1
          sudo microceph.ceph config set global osd_memory_target 939524096
          sudo microceph.ceph osd crush rule rm replicated_rule
          sudo microceph.ceph osd crush rule create-replicated replicated default osd
          for flag in nosnaptrim nobackfill norebalance norecover noscrub nodeep-scrub; do
              sudo microceph.ceph osd set "${flag}"
          done

          # If there is more than one OSD, set up partitions.
          if [ "${INPUTS_OSD_COUNT}" -gt 1 ]; then
            sudo blkdiscard "${ephemeral_disk}" --force
            sudo parted "${ephemeral_disk}" --script mklabel gpt

            for i in $(seq 1 "${INPUTS_OSD_COUNT}"); do
              # Create equal sized partitions for each OSD.
              min="$(( (i-1) *  100 / INPUTS_OSD_COUNT ))"
              max="$(( i * 100 / INPUTS_OSD_COUNT ))"
              sudo parted "${ephemeral_disk}" --align optimal --script mkpart primary "${min}%" "${max}%"
            done

            # Force the detection of the new partitions
            sudo partx --update "${ephemeral_disk}"

            # Allow (more) time for the kernel to pick up the new partitions
            disk_name="$(basename "${ephemeral_disk}")"
            for _ in 1 2 3; do
              parts="$(grep -cwE "${disk_name}[0-9]+$" /proc/partitions)"
              [ "${parts}" -ge "${INPUTS_OSD_COUNT}" ] && break
              sleep 1
            done

            for i in $(seq 1 "${INPUTS_OSD_COUNT}"); do
              # MicroCeph does not accept partitions directly.
              # See: https://github.com/canonical/microceph/issues/251
              disk="$(sudo losetup --find --nooverlap --direct-io=on --show "${ephemeral_disk}${i}")"

              # Retry logic for "microceph disk add" that can fail due to partitions not being ready
              # Error: unable to list system disks: Failed to find "/dev/disk/by-id/scsi-36...9e-part1": lstat /dev/disk/by-id/scsi-36...9e-part1: no such file or directory
              wipe=""
              for attempt in 1 2 3; do
                if sudo microceph disk add "${disk}" ${wipe}; then
                  break # Success, exit retry loop
                elif [ "${attempt}" -lt 3 ]; then
                  echo "WARN: \"microceph disk add ${disk}\" failed, retrying with \"--wipe\" (${attempt}/3)"
                  # Clear any leftover data on the disk when retrying
                  wipe="--wipe"
                  sleep 1
                else
                  echo "FAIL: \"microceph disk add ${disk}\" failed ${attempt} times"
                  exit 1
                fi
              done
            done
          else
              sudo microceph disk add --wipe "${ephemeral_disk}"
          fi

          sudo rm -f /snap/bin/rbd
          sudo rm -rf /etc/ceph
          sudo ln -s /var/snap/microceph/current/conf/ /etc/ceph
          sudo microceph enable rgw
          sudo microceph.ceph osd pool create cephfs_meta 32
          sudo microceph.ceph osd pool create cephfs_data 32
          sudo microceph.ceph fs new cephfs cephfs_meta cephfs_data
          sudo microceph.ceph fs ls

    - name: Install ceph-common package
      shell: bash
      run: |
          set -eux

          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ceph-common
          # reclaim some space
          sudo apt-get clean

    - name: Wait for MicroCeph to be ready
      shell: bash
      run: |
          set -eux

          sudo microceph.ceph status
          # Wait until there are no more "unknowns" pgs
          for _ in $(seq 60); do
            if sudo microceph.ceph pg stat | grep -wF unknown; then
              sleep 1
            else
              break
            fi
          done
          sudo microceph.ceph status
