name: Setup MicroCeph
description: Setup MicroCeph to use the ephemeral disk of GHA runners

inputs:
  microceph-channel:
    description: MicroCeph snap channel to install
    default: "latest/edge"
    required: false
  osd-count:
    description: Number of OSDs to add to MicroCeph
    default: "1"
    required: false
  snap-cache-dir:
    description: Directory to use for snap cache
    default: "/home/runner/snap-cache"
    required: false

runs:
  using: composite
  steps:
    - name: Ephemeral disk checks
      shell: bash
      run: |
          set -eux

          # If the rootfs and the ephemeral part are on the same physical disk, giving the whole
          # disk to microceph would wipe our rootfs. Since it is pretty rare for GitHub Action
          # runners to have a single disk, we immediately bail rather than trying to gracefully
          # handle it.
          if [ "$(stat -c '%d' /)" = "$(stat -c '%d' /mnt)" ]; then
            echo "FAIL: rootfs and ephemeral part on the same disk, aborting"
            exit 1
          fi

    - name: Free-up ephemeral disk
      shell: bash
      id: free_ephemeral_disk
      run: |
          set -eux

          # Avoid LXD snap holding on to swap (https://github.com/canonical/lxd/issues/14768)
          sudo snap remove --purge lxd || true

          sudo swapoff /mnt/swapfile
          ephemeral_disk="$(findmnt --noheadings --output SOURCE --target /mnt | sed 's/[0-9]\+$//')"
          sudo umount /mnt
          echo "ephemeral_disk=${ephemeral_disk}" >> "${GITHUB_OUTPUT}"

    - name: Install MicroCeph snap
      shell: bash
      env:
        SNAP_CACHE_DIR: ${{ inputs.snap-cache-dir }}
        SNAP_CHANNEL: ${{ inputs.microceph-channel }}
      run: |
          set -eux
          # External repos using this action won't have access to the `test/includes/snap.sh` file
          # so install directly from the store instead.
          sudo --preserve-env=SNAP_CACHE_DIR "${GITHUB_ACTION_PATH}/setup-microceph.sh" install-microceph "${SNAP_CHANNEL}"

    - name: Configure MicroCeph snap
      shell: bash
      env:
        EPHEMERAL_DISK: ${{ steps.free_ephemeral_disk.outputs.ephemeral_disk }}
        INPUTS_OSD_COUNT: ${{ inputs.osd-count }}
      run: |
          set -eux
          sudo "${GITHUB_ACTION_PATH}/setup-microceph.sh" configure-microceph "${EPHEMERAL_DISK}" "${INPUTS_OSD_COUNT}"

    - name: Install ceph-common package
      shell: bash
      run: |
          set -eux
          sudo "${GITHUB_ACTION_PATH}/setup-microceph.sh" install-ceph-common

    - name: Wait for MicroCeph to be ready
      shell: bash
      run: |
          set -eux
          sudo "${GITHUB_ACTION_PATH}/setup-microceph.sh" wait-for-microceph
