// Command dbgen inspects tagged structs and generates interface implementations for them
// such that they can be used easily with generic functions defined in lxd/db/query/generic.go.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"strings"

	"golang.org/x/exp/maps"
)

// unqualifiedColumnNameRegex matches a column name, without a prefixed `<table>.` qualifier.
// It is used to check for shorthand column name labels. If a label matches this regular expression, it is
// prepended with `<table>.` for generated select statements. Any other tag that does not match this expression is
// used directly.
var unqualifiedColumnNameRegex = regexp.MustCompile(`^[_a-z]+$`)

func main() {
	err := run()
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
}

func run() error {
	if len(os.Args) < 2 {
		return errors.New("Package directory must be provided")
	}

	if len(os.Args) < 3 {
		return errors.New("Output file name must be provided")
	}

	if len(os.Args) > 3 {
		return errors.New("Unknown additional arguments")
	}

	// Directory to inspect.
	packageDirectory := os.Args[1]
	info, err := os.Stat(packageDirectory)
	if err != nil {
		return fmt.Errorf("Cannot stat package directory: %w", err)
	}

	if !info.IsDir() {
		return fmt.Errorf("%q is not a directory", packageDirectory)
	}

	// File to output relative to the package directory.
	outputFileName := os.Args[2]

	packageName, packageSpecs, err := getPackageSpecs(packageDirectory)
	if err != nil {
		return err
	}

	return writeOutputFile(packageName, packageSpecs, filepath.Join(packageDirectory, outputFileName))
}

// writeOutputFile executes all the spec templates and writes them to the output file path.
func writeOutputFile(packageName string, packageSpecs []Spec, outputFilePath string) error {
	var b bytes.Buffer

	// Write file header.
	b.WriteString("//go:build linux && cgo && !agent\n\n")
	b.WriteString("package " + packageName + "\n\n")
	b.WriteString("// Generated by dbgen - DO NOT EDIT\n")

	// Execute the template for each spec and write to the buffer.
	for _, spec := range packageSpecs {
		err := specSelectTemplate.Execute(&b, spec.templateContext())
		if err != nil {
			return err
		}

		// If the spec contains any joins we can't use it for any mutations, so skip the exec template.
		if len(spec.Joins) > 0 {
			continue
		}

		err = specExecTemplate.Execute(&b, spec.templateContext())
		if err != nil {
			return err
		}
	}

	// Create and write to file.
	outFile, err := os.Create(outputFilePath)
	if err != nil {
		return err
	}

	defer outFile.Close()
	_, err = b.WriteTo(outFile)
	if err != nil {
		return err
	}

	return nil
}

// getPackageSpecs parses each .go file in the package and creates a spec for each tagged struct.
func getPackageSpecs(packageDirectory string) (string, []Spec, error) {
	paths, err := filepath.Glob(filepath.Join(packageDirectory, "*.go"))
	if err != nil {
		return "", nil, fmt.Errorf("Failed listing package files: %w", err)
	}

	var allSpecs []Spec
	var pkgName string
	deferredDecls := make(map[*ast.StructType]*Spec)
	for _, path := range paths {
		// Parse file AST.
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			return "", nil, fmt.Errorf("Failed parsing Go source file %q: %w", path, err)
		}

		// Set the package name if not already set.
		if pkgName == "" {
			pkgName = file.Name.Name
		}

		fileSpecs, deferredSpecs, err := getFileSpecs(file)
		if err != nil {
			return "", nil, err
		}

		maps.Copy(deferredDecls, deferredSpecs)
		allSpecs = append(allSpecs, fileSpecs...)
	}

	allSpecs, err = getDeferredSpecs(allSpecs, deferredDecls)
	if err != nil {
		return "", nil, err
	}

	return pkgName, allSpecs, nil
}

// getFileSpecs returns a Spec for each tagged struct in the file.
func getFileSpecs(f *ast.File) ([]Spec, map[*ast.StructType]*Spec, error) {
	deferredDecls := make(map[*ast.StructType]*Spec, len(f.Decls))
	specs := make([]Spec, 0, len(f.Decls))

	for _, decl := range f.Decls {
		// Skip any declarations that:
		// - Are are not type declarations.
		// - Don't have comments.
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE || genDecl.Doc == nil || len(genDecl.Doc.List) == 0 || len(genDecl.Specs) != 1 {
			continue
		}

		// Skip any types that are not structs.
		typeSpec, ok := genDecl.Specs[0].(*ast.TypeSpec)
		if !ok {
			continue
		}

		structTypeSpec, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			continue
		}

		// The table name is defined by the db:model tag (a bit like swagger).
		var tableName, configTableName, configTableForeignKey string
		for _, comment := range genDecl.Doc.List {
			if !strings.HasPrefix(comment.Text, "// db:") {
				continue
			}

			table, ok := strings.CutPrefix(comment.Text, "// db:model ")
			if ok {
				tableName = table
				continue
			}

			configFields, ok := strings.CutPrefix(comment.Text, "// db:config ")
			if ok {
				configTableName, configTableForeignKey, ok = strings.Cut(configFields, " ")
				if !ok {
					return nil, nil, fmt.Errorf("Malformed config table spec for struct %q", typeSpec.Name.Name)
				}
			}
		}

		// Skip if no db:model tag is found.
		if tableName == "" {
			continue
		}

		newSpec := &Spec{
			TableName:        tableName,
			StructName:       typeSpec.Name.Name,
			ConfigTableName:  configTableName,
			ConfigForeignKey: configTableForeignKey,
		}

		// Iterate over the struct fields.
		var deferred bool
		for _, field := range structTypeSpec.Fields.List {
			if field.Tag == nil {
				// If the field does not have a tag, it is referencing another model.

				// For now, only allow one referenced struct per model.
				if deferred {
					return nil, nil, fmt.Errorf("More than one referenced field for struct %q", newSpec.StructName)
				}

				// For now, only allow referenced structs to appear first in the outer struct.
				if len(newSpec.Fields) > 0 {
					return nil, nil, fmt.Errorf("Referenced field in struct %q must appear first", newSpec.StructName)
				}

				// The field is a referenced model without a tag.
				// We continue parsing remaining fields, but defer parsing of the referenced type until later
				// because we need to get it from the spec list and it may not have been parsed yet.
				deferredDecls[structTypeSpec] = newSpec
				deferred = true
				continue
			}

			// Set the field name. This is used to map database columns to struct values.
			newFieldSpec := FieldSpec{
				FieldName: field.Names[0].Name,
			}

			// Tags only contain column names.
			newFieldSpec.ColumnName = reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("db")
			if newFieldSpec.ColumnName == "" {
				continue
			}

			// Check if it is only the column name (without the table name as a qualifier)
			// If it is only the column name, prepend the table name so that it is fully qualified.
			if unqualifiedColumnNameRegex.MatchString(newFieldSpec.ColumnName) {
				newFieldSpec.ColumnName = tableName + "." + newFieldSpec.ColumnName
			}

			// Check the field comment. Use "db:join" to specify joins required to get the value.
			if field.Doc != nil {
				for _, l := range field.Doc.List {
					join, ok := strings.CutPrefix(l.Text, "// db:join ")
					if ok {
						newSpec.Joins = append(newSpec.Joins, join)
						break
					}
				}
			}

			// Hardcode primary key as "id" column, as that is always true in LXD.
			if newFieldSpec.ColumnName == tableName+".id" {
				newSpec.PrimaryKey = newFieldSpec
			}

			newSpec.Fields = append(newSpec.Fields, newFieldSpec)
		}

		// If not deferred, validate and append to spec list.
		if !deferred {
			if newSpec.PrimaryKey.FieldName == "" {
				return nil, nil, fmt.Errorf("Cannot find a primary key for struct %q", newSpec.StructName)
			}

			if len(newSpec.Fields) == 0 {
				return nil, nil, errors.New("Table spec must have at least one field")
			}

			specs = append(specs, *newSpec)
		}
	}

	return specs, deferredDecls, nil
}

func getDeferredSpecs(allSpecs []Spec, deferredDecls map[*ast.StructType]*Spec) ([]Spec, error) {
	for structTypeSpec, newSpec := range deferredDecls {
		if newSpec.PrimaryKey.FieldName != "" {
			return nil, fmt.Errorf("Struct %q contains both a referenced type and a primary key", newSpec.StructName)
		}

		// The first field in the list is the referenced model.
		// This is enforced when parsing file specs.
		fieldName := structTypeSpec.Fields.List[0].Names[0].Name

		// Get the type of the referenced field.
		ident, ok := structTypeSpec.Fields.List[0].Type.(*ast.Ident)
		if !ok {
			return nil, fmt.Errorf("Struct %q contains an untagged field whose type is not a struct", newSpec.StructName)
		}

		ts, ok := ident.Obj.Decl.(*ast.TypeSpec)
		if !ok {
			return nil, fmt.Errorf("Struct %q contains an untagged field whose type is not a struct", newSpec.StructName)
		}

		// The referenced field must be a struct (because it is another modelled struct).
		_, ok = ts.Type.(*ast.StructType)
		if !ok {
			return nil, fmt.Errorf("Struct %q contains an untagged field whose type is not a struct", newSpec.StructName)
		}

		// Find the spec with the same struct name as the referenced type.
		idx := slices.IndexFunc(allSpecs, func(spec Spec) bool {
			return spec.StructName == ident.Name
		})

		if idx == -1 {
			return nil, fmt.Errorf("Modelled type %q contains struct %q which is not modelled", newSpec.StructName, ident.Name)
		}

		spec := allSpecs[idx]

		// Both specs must model the same table.
		if spec.TableName != newSpec.TableName {
			return nil, fmt.Errorf("Modelled type %q contains struct %q which models a different table", newSpec.StructName, ident.Name)
		}

		// Prepend fields from the referenced struct. The referenced struct is enforced to be the first field when parsing file specs.
		newSpec.ReferenceFieldName = fieldName
		newSpec.Reference = &spec
		allSpecs = append(allSpecs, *newSpec)
		delete(deferredDecls, structTypeSpec)
	}

	if len(deferredDecls) > 0 {
		return nil, errors.New("Referenced models may not reference other models")
	}

	return allSpecs, nil
}
