name: Setup SSH for integration with snap build on Launchpad
description: |
  This action sets up SSH access to Launchpad for pushing and pulling code and signing commits.
  It also configures Git with the necessary settings for signing commits.
  It clones the snap packaging repository into ~/${PACKAGE}-pkg-snap-lp
  Lastly it installs the `lxd-snapcraft` tool to allow modifying the snapcraft.yaml file.

  It relies on some environment variables being set:
  - `SSH_AUTH_SOCK`: The path to the SSH agent socket.
  - `REPO`: The URL of the snap packaging repository.
  - `BRANCH`: The branch to clone from the snap packaging repository.
  - `PACKAGE`: The name of the snap package.

inputs:
  ssh-key:
    description: The private SSH key for pulling/pushing to Launchpad and commit signing.
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        set -eux
        git config --global transfer.fsckobjects true
        git config --global user.name "Canonical LXD Bot"
        git config --global user.email "lxd@lists.canonical.com"
        git config --global commit.gpgsign true
        git config --global gpg.format "ssh"
        git config --global user.signingkey ~/.ssh/id_ed25519.pub

    - name: Install lxd-snapcraft tool
      shell: bash
      run: |
        # Depends on Go being available which is the case in the GitHub Actions environment
        set -eux
        if [ -d "${GITHUB_WORKSPACE}/lxd-snapcraft" ]; then
          # Install from the checked-out repository when running in lxd-pkg-snap
          go -C "${GITHUB_WORKSPACE}/lxd-snapcraft" install .
        else
          # Install from the same ref the action was pinned to by the caller
          go install "github.com/canonical/lxd-pkg-snap/lxd-snapcraft@${GITHUB_ACTION_REF}"
        fi

        # Move the binary into its final location in PATH
        sudo mv ~/go/bin/lxd-snapcraft /usr/local/bin/

    - name: Seed Launchpad SSH host key
      shell: bash
      run: |
        set -eux
        mkdir -m 0700 -p ~/.ssh/
        # Seed known_hosts with the expected RSA key (fingerprint: SHA256:UNOzlP66WpDuEo34Wgs8mewypV0UzqHLsIFoqwe8dYo)
        # from https://documentation.ubuntu.com/launchpad/user/reference/ssh-fingerprints/
        echo 'git.launchpad.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEFREwBD2ye2Xrc2SVcUmmJ44MF1BCB3W11NTaiqzVj7XZnQmgWZk9UadHVY2wBXvelcDO51MPN5ozJjFAknw09rP7XMRJMlAOLSIVoU6DRF1u1j8kJVY+dfiDHheS7+siADnrmb8HGn2xQQ6EJDjAXrw1x58x5eZjQ0PFWdI+pRTdYGvWkpHdXKFO6a9/lDx4uo9MCnePEGi/QnkCmKqLCBUlYNZYRiB8nVee2tMF0mjV8xk1rJ+/UP+897+FXFR9w/B1EPRjiQ35ZNQZKPP4isxPtyMuCQkZY7ckWr5YsylNfvNcyGDnO1XazZhJ71rzDpi1RmnFXBW5i+2dm2y7' > ~/.ssh/known_hosts

    # XXX: from this point onwards, the action has access to the private SSH key
    #      either as an environment variable or through the SSH agent
    - name: Setup Launchpad SSH access
      shell: bash
      env:
        INPUTS_SSH_KEY: ${{ inputs.ssh-key }}
      run: |
        set -eu # let's not use -x here to avoid leaking the SSH key in the logs
        ssh-agent -a "${SSH_AUTH_SOCK}" > /dev/null
        ssh-add - <<< "${INPUTS_SSH_KEY}"
        unset INPUTS_SSH_KEY
        ssh-add -L > ~/.ssh/id_ed25519.pub

    - name: Git clone repository
      shell: bash
      run: |
        set -eux
        git clone --depth 1 -b "${BRANCH}" "${REPO}" ~/"${PACKAGE}-pkg-snap-lp"
