name: Install LXD build dependencies
description: Installs LXD build dependencies

runs:
  using: composite
  steps:
    - name: Installs LXD build dependencies
      shell: bash
      run: |
        set -eux
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          build-essential \
          curl \
          dpkg-dev \
          gettext \
          git \
          libacl1-dev \
          libcap-dev \
          libdbus-1-dev \
          libgnutls28-dev \
          lxc-templates \
          libseccomp-dev \
          libselinux1-dev \
          libsqlite3-dev \
          libtool \
          libudev-dev \
          libuv1-dev \
          make \
          meson \
          ninja-build \
          pkg-config \
          shellcheck

        # reclaim some space
        sudo apt-get clean
