#!/bin/sh
run_cmd() {
    CMD="$1"
    shift

    unset LD_LIBRARY_PATH
    export PATH="/run/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    export HOME="${SNAP_REAL_HOME}"
    export USER="${USERNAME}"

    exec unshare -U -r chroot "/var/lib/snapd/hostfs/" "${CMD}" "$@"
}

USERNS=1
[ -e /proc/sys/kernel/unprivileged_userns_clone ] && grep -qxF 0 /proc/sys/kernel/unprivileged_userns_clone && USERNS=0
[ -e /proc/sys/kernel/apparmor_restrict_unprivileged_userns ] && grep -qxF 1 /proc/sys/kernel/apparmor_restrict_unprivileged_userns && USERNS=0

find_and_spawn() {
    for path in /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin; do
        if [ -x "/var/lib/snapd/hostfs/${path}/remote-viewer" ]; then
            run_cmd "${path}/remote-viewer" "${1}"
            return
        fi

        if [ -x "/var/lib/snapd/hostfs/${path}/spicy" ]; then
            run_cmd "${path}/spicy" --uri="${1}"
            return
        fi
    done
}

[ "${USERNS}" = "1" ] && find_and_spawn "${1}"

echo "LXD relies on either remote-viewer or spicy to provide VGA console access."
echo "Those can't be bundled with the LXD snap and so need to be manually installed."
echo ""
echo " - \"remote-viewer\" usually comes in a package called virt-viewer"
echo " - \"spicy\" usually comes in a package called spice-client-gtk"
echo ""
echo "Install either of those and they will automatically start."
echo "Alternatively you may use another SPICE client using the following URI:"
echo "  ${1}"

if [ "${USERNS}" = "0" ]; then
    echo ""
    echo "Your system has unprivileged user namespaces disabled, as a result, "
    echo "you will need to manually run a SPICE client with the URI above."
    exec sleep infinity
else
    while :; do
        find_and_spawn "${1}"
        sleep 5s
    done
fi
