#!/bin/sh
# Turn `/usr/sbin/foo` into `foo`
# Similar to `basename` but using variable substitution instead of external executable
CMD="${0##*/}"

unset LD_LIBRARY_PATH
unset PYTHONPATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if [ "$(id -u)" = "0" ]; then
    exec nsenter -t 1 -m "${CMD}" "$@"
fi

exec unshare -U -r --root="/var/lib/snapd/hostfs/" "${CMD}" "$@"
