name: Tune disk performance
description: Optimize ext4 FSes for performance, not reliability

runs:
  using: composite
  steps:
    - name: Tune disk performance
      shell: bash
      run: |
        set -eux
        # optimize ext4 FSes for performance, not reliability
        for fs in $(findmnt --noheading --type ext4 --list --uniq | awk '{print $1}'); do
          # nombcache and data=writeback cannot be changed on remount
          sudo mount -o remount,noatime,barrier=0,commit=6000 "${fs}" || true
        done

        # disable dpkg from calling sync()
        echo "force-unsafe-io" | sudo tee /etc/dpkg/dpkg.cfg.d/force-unsafe-io
