name: Cache dqlite/liblxc dependencies
description: Restore dqlite/liblxc from the daily cache or build them

runs:
  using: composite
  steps:
    - name: deps cache key
      id: deps-cache-key
      shell: bash
      run: |
        set -eux
        . /etc/os-release
        ARCH="$(dpkg --print-architecture)"
        DATE="$(date --utc '+%Y%m%d')"
        YESTERDAY="$(date --utc '+%Y%m%d' --date=yesterday)"

        # dqlite/liblxc deps cache key
        eval "$(grep -E '^(DQLITE|LIBLXC)_BRANCH=' Makefile)"

        # i.e: deps-ubuntu-24.04-amd64-dqlite-main-liblxc-main-${DATE}
        KEY_PREFIX="deps-${ID}-${VERSION_ID}-${ARCH}-dqlite-${DQLITE_BRANCH}-liblxc-${LIBLXC_BRANCH}"
        echo "KEY=${KEY_PREFIX}-${DATE}" >> $GITHUB_OUTPUT
        echo "FALLBACK_KEY=${KEY_PREFIX}-${YESTERDAY}" >> $GITHUB_OUTPUT

    # GitHub will remove any cache entries that have not been accessed in over 7 days.
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
    - name: Cache dqlite/liblxc deps
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache-deps
      with:
        path: |
          /home/runner/go/bin/dqlite
          /home/runner/go/bin/liblxc
        key: ${{ steps.deps-cache-key.outputs.KEY }}
        restore-keys: |
          ${{ steps.deps-cache-key.outputs.FALLBACK_KEY }}

    - name: Build LXD dependencies
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -eux

        # It's possible to get here despite doing a cache-hit because when one
        # of the restore-keys is used as fallback, the outputs.cache-hit is set
        # to false. As such, check if the directories are present and if so,
        # bail out early.
        if [ -n "$(ls -A "/home/runner/go/bin/dqlite/")" ] && [ -n "$(ls -A "/home/runner/go/bin/liblxc/")" ]; then
          echo "==> SKIP building as dqlite and liblxc deps were restored from fallback key"
          exit 0
        fi

        # Build from unpacked dist tarball.
        cd /home/runner/work/lxd/lxd-test
        make deps

        # Include dqlite libs in dependencies for system tests.
        mkdir -p /home/runner/go/bin/dqlite
        mv /home/runner/work/lxd/lxd-test/vendor/dqlite/include /home/runner/go/bin/dqlite/include
        mv /home/runner/work/lxd/lxd-test/vendor/dqlite/.libs /home/runner/go/bin/dqlite/libs

        # Include liblxc libs in dependencies for system tests.
        mkdir -p /home/runner/go/bin/liblxc
        mv /home/runner/work/lxd/lxd-test/vendor/liblxc/include /home/runner/go/bin/liblxc/include
        mv /home/runner/work/lxd/lxd-test/vendor/liblxc/lib /home/runner/go/bin/liblxc/libs

        # liblxc requires a rootfs dir
        mkdir -p /home/runner/go/bin/liblxc/rootfs
