#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Check that we're root
if [ "$(id -u)" != "0" ]; then
    echo "error: This tool must be run as root."
    exit 1
fi

# shellcheck disable=SC2155
export SNAP_CURRENT="$(realpath "${SNAP}/..")/current"

export LXD_DIR="${LXD_DIR:-"${SNAP_COMMON}/lxd/"}"
export LXD_CONF="${SNAP_USER_COMMON}/config"

exec "${SNAP_CURRENT}/bin/lxc-to-lxd" "$@"
