#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Set the environment
export LXD_DIR="${LXD_DIR:-"${SNAP_COMMON}/lxd/"}"
export PATH="/run/bin:${PATH}"

# Reset all locales as it isn't available in the snap (#29)
LANG=C.UTF-8
export LC_ALL=C.UTF-8

# Relocate to storage dir
mkdir -p "${SNAP_COMMON}/lxd-user/"
chmod 0711 "${SNAP_COMMON}/lxd-user/"
cd "${SNAP_COMMON}/lxd-user/"

# Run lxd-user
exec lxd-user
