#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
label="$(cat /proc/self/attr/current 2>/dev/null || echo "unconfined")"
if [ "${label}" != "unconfined" ] && [ -n "${label##*(unconfined)}" ]; then
  exec aa-exec -p unconfined -- "$0" "$@"
fi

exec lxc-checkconfig
