//go:build linux && cgo && !agent

package cluster

// Generated by dbgen - DO NOT EDIT

// TableName returns the table name for [AuthGroupsRow] entities.
func (a AuthGroupsRow) TableName() string {
	return "auth_groups"
}

// SelectColumns returns a slice of column names for [AuthGroupsRow] entities.
func (a AuthGroupsRow) SelectColumns() []string {
	return []string{
		"auth_groups.id",
		"auth_groups.name",
		"auth_groups.description",
	}
}

// Joins returns a slice of join expressions for [AuthGroupsRow].
func (a AuthGroupsRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [AuthGroupsRow].
// This returns references to struct fields in definition order.
func (a *AuthGroupsRow) ScanArgs() []any {
	return []any{&a.ID, &a.Name, &a.Description}
}

// CreateValues returns a list of values from [AuthGroupsRow] entities matching the columns returned from CreateColumns.
func (a AuthGroupsRow) CreateValues() []any {
	return []any{a.Name, a.Description}
}

// PKColumn returns the column name for the primary key of a [AuthGroupsRow] entity used during an update.
func (a AuthGroupsRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [AuthGroupsRow] entity used during an update.
func (a AuthGroupsRow) PKValue() any {
	return a.ID
}

// CreateStmt returns a query that creates a [AuthGroupsRow] entity.
func (a AuthGroupsRow) CreateStmt() string {
	return "INSERT INTO auth_groups (name, description) VALUES (?, ?)"
}

// UpdateStmt returns a query that updates a [AuthGroupsRow] by primary key.
func (a AuthGroupsRow) UpdateStmt() string {
	return "UPDATE auth_groups SET name = ?, description = ? "
}
