//go:build linux && cgo && !agent

package cluster

// Generated by dbgen - DO NOT EDIT

// TableName returns the table name for [AuthGroupsRow] entities.
func (a AuthGroupsRow) TableName() string {
	return "auth_groups"
}

// SelectColumns returns a slice of column names for [AuthGroupsRow] entities.
func (a AuthGroupsRow) SelectColumns() []string {
	return []string{
		"auth_groups.id",
		"auth_groups.name",
		"auth_groups.description",
	}
}

// Joins returns a slice of join expressions for [AuthGroupsRow].
func (a AuthGroupsRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [AuthGroupsRow].
// This returns references to struct fields in definition order.
func (a *AuthGroupsRow) ScanArgs() []any {
	return []any{&a.ID, &a.Name, &a.Description}
}

// CreateValues returns a list of values from [AuthGroupsRow] entities matching the bind arguments in [CreateStmt].
func (a AuthGroupsRow) CreateValues() []any {
	return []any{a.Name, a.Description}
}

// UpdateValues returns a list of values from [AuthGroupsRow] entities matching the columns in [UpdateStmt].
func (a AuthGroupsRow) UpdateValues() []any {
	return []any{a.Name, a.Description}
}

// PKColumn returns the column name for the primary key of a [AuthGroupsRow] entity used during an update.
func (a AuthGroupsRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [AuthGroupsRow] entity used during an update.
func (a AuthGroupsRow) PKValue() any {
	return a.ID
}

// CreateStmt returns a query that creates a [AuthGroupsRow] entity.
func (a AuthGroupsRow) CreateStmt() string {
	return "INSERT INTO auth_groups (name, description) VALUES (?, ?)"
}

// UpdateStmt returns a query that updates a [AuthGroupsRow] by primary key.
func (a AuthGroupsRow) UpdateStmt() string {
	return "UPDATE auth_groups SET name = ?, description = ? "
}

// TableName returns the table name for [CertificatesRow] entities.
func (c CertificatesRow) TableName() string {
	return "certificates"
}

// SelectColumns returns a slice of column names for [CertificatesRow] entities.
func (c CertificatesRow) SelectColumns() []string {
	return []string{
		"certificates.id",
		"certificates.fingerprint",
		"certificates.certificate",
		"certificates.creation_date",
	}
}

// Joins returns a slice of join expressions for [CertificatesRow].
func (c CertificatesRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [CertificatesRow].
// This returns references to struct fields in definition order.
func (c *CertificatesRow) ScanArgs() []any {
	return []any{&c.ID, &c.Fingerprint, &c.Certificate, &c.CreationDate}
}

// CreateValues returns a list of values from [CertificatesRow] entities matching the bind arguments in [CreateStmt].
func (c CertificatesRow) CreateValues() []any {
	return []any{c.Fingerprint, c.Certificate}
}

// UpdateValues returns a list of values from [CertificatesRow] entities matching the columns in [UpdateStmt].
func (c CertificatesRow) UpdateValues() []any {
	return []any{c.Fingerprint, c.Certificate}
}

// PKColumn returns the column name for the primary key of a [CertificatesRow] entity used during an update.
func (c CertificatesRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [CertificatesRow] entity used during an update.
func (c CertificatesRow) PKValue() any {
	return c.ID
}

// CreateStmt returns a query that creates a [CertificatesRow] entity.
func (c CertificatesRow) CreateStmt() string {
	return "INSERT INTO certificates (fingerprint, certificate) VALUES (?, ?)"
}

// UpdateStmt returns a query that updates a [CertificatesRow] by primary key.
func (c CertificatesRow) UpdateStmt() string {
	return "UPDATE certificates SET fingerprint = ?, certificate = ? "
}

// TableName returns the table name for [ClusterLinkRow] entities.
func (c ClusterLinkRow) TableName() string {
	return "cluster_links"
}

// SelectColumns returns a slice of column names for [ClusterLinkRow] entities.
func (c ClusterLinkRow) SelectColumns() []string {
	return []string{
		"cluster_links.id",
		"cluster_links.identity_id",
		"cluster_links.name",
		"cluster_links.description",
		"cluster_links.type",
	}
}

// Joins returns a slice of join expressions for [ClusterLinkRow].
func (c ClusterLinkRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [ClusterLinkRow].
// This returns references to struct fields in definition order.
func (c *ClusterLinkRow) ScanArgs() []any {
	return []any{&c.ID, &c.IdentityID, &c.Name, &c.Description, &c.Type}
}

// CreateValues returns a list of values from [ClusterLinkRow] entities matching the bind arguments in [CreateStmt].
func (c ClusterLinkRow) CreateValues() []any {
	return []any{c.IdentityID, c.Name, c.Description, c.Type}
}

// UpdateValues returns a list of values from [ClusterLinkRow] entities matching the columns in [UpdateStmt].
func (c ClusterLinkRow) UpdateValues() []any {
	return []any{c.IdentityID, c.Name, c.Description, c.Type}
}

// PKColumn returns the column name for the primary key of a [ClusterLinkRow] entity used during an update.
func (c ClusterLinkRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [ClusterLinkRow] entity used during an update.
func (c ClusterLinkRow) PKValue() any {
	return c.ID
}

// CreateStmt returns a query that creates a [ClusterLinkRow] entity.
func (c ClusterLinkRow) CreateStmt() string {
	return "INSERT INTO cluster_links (identity_id, name, description, type) VALUES (?, ?, ?, ?)"
}

// UpdateStmt returns a query that updates a [ClusterLinkRow] by primary key.
func (c ClusterLinkRow) UpdateStmt() string {
	return "UPDATE cluster_links SET identity_id = ?, name = ?, description = ?, type = ? "
}

// TableName returns the table name for [IdentitiesRow] entities.
func (i IdentitiesRow) TableName() string {
	return "identities"
}

// SelectColumns returns a slice of column names for [IdentitiesRow] entities.
func (i IdentitiesRow) SelectColumns() []string {
	return []string{
		"identities.id",
		"identities.auth_method",
		"identities.type",
		"identities.identifier",
		"identities.name",
		"identities.metadata",
	}
}

// Joins returns a slice of join expressions for [IdentitiesRow].
func (i IdentitiesRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [IdentitiesRow].
// This returns references to struct fields in definition order.
func (i *IdentitiesRow) ScanArgs() []any {
	return []any{&i.ID, &i.AuthMethod, &i.Type, &i.Identifier, &i.Name, &i.Metadata}
}

// CreateValues returns a list of values from [IdentitiesRow] entities matching the bind arguments in [CreateStmt].
func (i IdentitiesRow) CreateValues() []any {
	return []any{i.AuthMethod, i.Type, i.Identifier, i.Name, i.Metadata}
}

// UpdateValues returns a list of values from [IdentitiesRow] entities matching the columns in [UpdateStmt].
func (i IdentitiesRow) UpdateValues() []any {
	return []any{i.AuthMethod, i.Type, i.Identifier, i.Name, i.Metadata}
}

// PKColumn returns the column name for the primary key of a [IdentitiesRow] entity used during an update.
func (i IdentitiesRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [IdentitiesRow] entity used during an update.
func (i IdentitiesRow) PKValue() any {
	return i.ID
}

// CreateStmt returns a query that creates a [IdentitiesRow] entity.
func (i IdentitiesRow) CreateStmt() string {
	return "INSERT INTO identities (auth_method, type, identifier, name, metadata) VALUES (?, ?, ?, ?, ?)"
}

// UpdateStmt returns a query that updates a [IdentitiesRow] by primary key.
func (i IdentitiesRow) UpdateStmt() string {
	return "UPDATE identities SET auth_method = ?, type = ?, identifier = ?, name = ?, metadata = ? "
}

// TableName returns the table name for [IdentityCertificate] entities.
func (i IdentityCertificate) TableName() string {
	return "certificates"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (i IdentityCertificate) APIName() string {
	return i.Row.APIName()
}

// SelectColumns returns a slice of column names for [IdentityCertificate] entities.
func (i IdentityCertificate) SelectColumns() []string {
	return []string{
		"certificates.id",
		"certificates.fingerprint",
		"certificates.certificate",
		"certificates.creation_date",
		"identities_certificates.identity_id",
	}
}

// Joins returns a slice of join expressions for [IdentityCertificate].
func (i IdentityCertificate) Joins() []string {
	return []string{
		"JOIN identities_certificates ON certificates.id = identities_certificates.certificate_id",
	}
}

// ScanArgs implements [query.ScanArger] for [IdentityCertificate].
// This returns references to struct fields in definition order.
func (i *IdentityCertificate) ScanArgs() []any {
	return []any{&i.Row.ID, &i.Row.Fingerprint, &i.Row.Certificate, &i.Row.CreationDate, &i.IdentityID}
}

// TableName returns the table name for [PlacementGroup] entities.
func (p PlacementGroup) TableName() string {
	return "placement_groups"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (p PlacementGroup) APIName() string {
	return p.Row.APIName()
}

// SelectColumns returns a slice of column names for [PlacementGroup] entities.
func (p PlacementGroup) SelectColumns() []string {
	return []string{
		"placement_groups.id",
		"placement_groups.name",
		"placement_groups.description",
		"placement_groups.project_id",
		"projects.name",
	}
}

// Joins returns a slice of join expressions for [PlacementGroup].
func (p PlacementGroup) Joins() []string {
	return []string{
		"JOIN projects ON placement_groups.project_id = projects.id",
	}
}

// ScanArgs implements [query.ScanArger] for [PlacementGroup].
// This returns references to struct fields in definition order.
func (p *PlacementGroup) ScanArgs() []any {
	return []any{&p.Row.ID, &p.Row.Name, &p.Row.Description, &p.Row.ProjectID, &p.ProjectName}
}

// TableName returns the table name for [PlacementGroupsRow] entities.
func (p PlacementGroupsRow) TableName() string {
	return "placement_groups"
}

// SelectColumns returns a slice of column names for [PlacementGroupsRow] entities.
func (p PlacementGroupsRow) SelectColumns() []string {
	return []string{
		"placement_groups.id",
		"placement_groups.name",
		"placement_groups.description",
		"placement_groups.project_id",
	}
}

// Joins returns a slice of join expressions for [PlacementGroupsRow].
func (p PlacementGroupsRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [PlacementGroupsRow].
// This returns references to struct fields in definition order.
func (p *PlacementGroupsRow) ScanArgs() []any {
	return []any{&p.ID, &p.Name, &p.Description, &p.ProjectID}
}

// CreateValues returns a list of values from [PlacementGroupsRow] entities matching the bind arguments in [CreateStmt].
func (p PlacementGroupsRow) CreateValues() []any {
	return []any{p.Name, p.Description, p.ProjectID}
}

// UpdateValues returns a list of values from [PlacementGroupsRow] entities matching the columns in [UpdateStmt].
func (p PlacementGroupsRow) UpdateValues() []any {
	return []any{p.Name, p.Description, p.ProjectID}
}

// PKColumn returns the column name for the primary key of a [PlacementGroupsRow] entity used during an update.
func (p PlacementGroupsRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [PlacementGroupsRow] entity used during an update.
func (p PlacementGroupsRow) PKValue() any {
	return p.ID
}

// CreateStmt returns a query that creates a [PlacementGroupsRow] entity.
func (p PlacementGroupsRow) CreateStmt() string {
	return "INSERT INTO placement_groups (name, description, project_id) VALUES (?, ?, ?)"
}

// UpdateStmt returns a query that updates a [PlacementGroupsRow] by primary key.
func (p PlacementGroupsRow) UpdateStmt() string {
	return "UPDATE placement_groups SET name = ?, description = ?, project_id = ? "
}
