// Package simplegen inspects tagged structs and generates interface implementations for them
// such that they can be used easily with generic functions defined in lxd/db/query/generic.go.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"
)

func main() {
	err := run()
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
}

func run() error {
	if len(os.Args) < 2 {
		return errors.New("Package directory must be provided")
	}

	if len(os.Args) < 3 {
		return errors.New("Output file name must be provided")
	}

	if len(os.Args) > 3 {
		return errors.New("Unknown additional arguments")
	}

	// Directory to inspect.
	packageDirectory := os.Args[1]
	info, err := os.Stat(packageDirectory)
	if err != nil {
		return fmt.Errorf("Cannot stat package directory: %w", err)
	}

	if !info.IsDir() {
		return fmt.Errorf("%q is not a directory", packageDirectory)
	}

	// File to output relative to the package directory.
	outputFileName := os.Args[2]

	packageName, packageSpecs, err := getPackageSpecs(packageDirectory)
	if err != nil {
		return err
	}

	return writeOutputFile(packageName, packageSpecs, filepath.Join(packageDirectory, outputFileName))
}

// writeOutputFile executes all the spec templates and writes them to the output file path.
func writeOutputFile(packageName string, packageSpecs []Spec, outputFilePath string) error {
	var b bytes.Buffer

	// Write file header.
	b.WriteString("//go:build linux && cgo && !agent\n\n")
	b.WriteString("package " + packageName + "\n\n")
	b.WriteString("// Generated by simplegen - DO NOT EDIT\n")

	// Execute the template for each spec and write to the buffer.
	for _, spec := range packageSpecs {
		err := specTemplate.Execute(&b, spec.templateContext())
		if err != nil {
			return err
		}
	}

	// Create and write to file.
	outFile, err := os.Create(outputFilePath)
	if err != nil {
		return err
	}

	defer outFile.Close()
	_, err = b.WriteTo(outFile)
	if err != nil {
		return err
	}

	return nil
}

// getPackageSpecs parses each .go file in the package and creates a spec for each tagged struct.
func getPackageSpecs(packageDirectory string) (packageName string, specs []Spec, err error) {
	paths, err := filepath.Glob(filepath.Join(packageDirectory, "*.go"))
	if err != nil {
		return "", nil, fmt.Errorf("Failed listing package files: %w", err)
	}

	var allSpecs []Spec
	var pkgName string
	for _, path := range paths {
		// Parse file AST.
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			return "", nil, fmt.Errorf("Failed parsing Go source file %q: %w", path, err)
		}

		// Set the package name if not already set.
		if pkgName == "" {
			pkgName = file.Name.Name
		}

		fileSpecs, err := getFileSpecs(file)
		if err != nil {
			return "", nil, err
		}

		allSpecs = append(allSpecs, fileSpecs...)
	}

	return pkgName, allSpecs, nil
}

// getFileSpecs returns a Spec for each tagged struct in the file.
func getFileSpecs(f *ast.File) ([]Spec, error) {
	specs := make([]Spec, 0, len(f.Decls))
	for _, decl := range f.Decls {
		// Skip any declarations that:
		// - Are are not type declarations.
		// - Don't have comments.
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE || genDecl.Doc == nil || len(genDecl.Doc.List) == 0 || len(genDecl.Specs) != 1 {
			continue
		}

		// The table name is defined by the db:model tag (a bit like swagger).
		tableName, ok := strings.CutPrefix(genDecl.Doc.List[len(genDecl.Doc.List)-1].Text, "// db:model ")
		if !ok {
			continue
		}

		newSpec := Spec{
			TableName: tableName,
		}

		// At this point we've found a "db:model" comment, so we expect to find a struct type definition.
		typeSpec, ok := genDecl.Specs[0].(*ast.TypeSpec)
		if !ok {
			return nil, fmt.Errorf("Encountered unexpected type spec %q", genDecl.Specs[0])
		}

		// Set the struct name. This is used in the receiver of the generated methods.
		newSpec.StructName = typeSpec.Name.Name

		structTypeSpec, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return nil, fmt.Errorf("Encountered unexpected struct type spec %q", genDecl.Specs[0])
		}

		// Iterate over the struct fields.
		for _, field := range structTypeSpec.Fields.List {
			// Fields without a tag are ignored.
			if field.Tag == nil {
				continue
			}

			// Set the field name. This is used to map database columns to struct values.
			newFieldSpec := FieldSpec{
				FieldName: field.Names[0].Name,
			}

			// Tags only contain column names.
			newFieldSpec.ColumnName = reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("db")
			if newFieldSpec.ColumnName == "" {
				continue
			}

			column, _, ok := strings.Cut(newFieldSpec.ColumnName, ".")
			if !ok {
				newFieldSpec.ColumnName = tableName + "." + column
			}

			// Check the field comment. Use "db:join" to specify joins required to get the value.
			if field.Doc != nil {
				for _, l := range field.Doc.List {
					join, ok := strings.CutPrefix(l.Text, "// db:join ")
					if ok {
						newSpec.Joins = append(newSpec.Joins, join)
						break
					}
				}
			}

			// Hardcode primary key as "id" column, as that is always true in LXD.
			if newFieldSpec.ColumnName == tableName+".id" {
				newSpec.PrimaryKey = newFieldSpec
			}

			newSpec.Fields = append(newSpec.Fields, newFieldSpec)
		}

		if newSpec.PrimaryKey.FieldName == "" {
			return nil, fmt.Errorf("Cannot find a primary key for struct %q", newSpec.StructName)
		}

		if len(newSpec.Fields) == 0 {
			return nil, errors.New("Table spec must have at least one field")
		}

		specs = append(specs, newSpec)
	}

	return specs, nil
}
