#!/usr/bin/env python3
import argparse
import os
import sys


def import_ubuntu(parser, args):
    remote = "ubuntu"

    if args.stream == "daily":
        remote = "ubuntu-daily"

    parts = []
    if args.release:
        parts.append(args.release)

    if args.architecture:
        parts.append(args.architecture)

    if args.version:
        parts.append(args.version)

    image = "/".join(parts)

    cmd = ["lxc", "image", "copy", "%s:%s" % (remote, image), "local:"]

    for alias in args.alias:
        cmd += ["--alias", alias]

    if args.public:
        cmd += ["--public"]

    if args.sync:
        cmd += ["--auto-update"]

    print("Redirecting to: %s" % " ".join(cmd), file=sys.stderr)
    os.execvp("lxc", cmd)


def import_busybox(parser, args):
    print("Redirecting to: test/deps/import-busybox %s" %
          " ".join(sys.argv[2:]), file=sys.stderr)
    os.execvp("test/deps/import-busybox",
              ["import-busybox"] + sys.argv[3:])


def sync(parser, args):
    print("Sync is now done by LXD itself.", file=sys.stderr)
    pass

parser = argparse.ArgumentParser("Compatibility wrapper")
parser.add_argument("--quiet", action="store_true")

parser_subparsers = parser.add_subparsers(dest="action")
parser_subparsers.required = True

# Image import
parser_import = parser_subparsers.add_parser("import")
parser_import_subparsers = parser_import.add_subparsers(dest="source")
parser_import_subparsers.required = True

# # Busybox
parser_import_busybox = parser_import_subparsers.add_parser("busybox")
parser_import_busybox.add_argument("--alias", action="append", default=[])
parser_import_busybox.add_argument("--public", action="store_true",
                                   default=False)
parser_import_busybox.add_argument("--split", action="store_true",
                                   default=False)
parser_import_busybox.set_defaults(func=import_busybox)

# # Ubuntu
parser_import_ubuntu = parser_import_subparsers.add_parser("ubuntu")
parser_import_ubuntu.add_argument("release", default=None, nargs="?")
parser_import_ubuntu.add_argument("architecture", default=None, nargs="?")
parser_import_ubuntu.add_argument("version",  default=None, nargs="?")
parser_import_ubuntu.add_argument("--stream", default="auto")
parser_import_ubuntu.add_argument("--alias", action="append", default=[])
parser_import_ubuntu.add_argument("--public", action="store_true",
                                  default=False)
parser_import_ubuntu.add_argument("--sync", action="store_true", default=False)
parser_import_ubuntu.set_defaults(func=import_ubuntu)

# Image sync
parser_import = parser_subparsers.add_parser("sync")
parser_import.set_defaults(func=sync)

# Call the function
args = parser.parse_args()

try:
    args.func(parser, args)
except Exception as e:
    parser.error(e)
