#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
label="$(cat /proc/self/attr/current 2>/dev/null || echo "unconfined")"
if [ "${label}" != "unconfined" ] && [ -n "${label##*(unconfined)}" ]; then
  exec aa-exec -p unconfined -- "$0" "$@"
fi

rm -f "${SNAP_COMMON}/use-qemu-external-snap"

echo reload > "${SNAP_COMMON}/state"
read -r PID < "${SNAP_COMMON}/lxd.pid"
kill "$PID"
