name: Copilot Setup Steps

# Automatically run the setup steps when they are changed to allow for easy
# validation, and allow manual testing through the repository's "Actions" tab.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions:
  contents: read

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-26.04

    env:
      CGO_CFLAGS: "-I/home/runner/go/deps/dqlite/include/ -I/home/runner/go/deps/liblxc/include/"
      CGO_LDFLAGS: "-L/home/runner/go/deps/dqlite/.libs/"
      LD_LIBRARY_PATH: "/home/runner/go/deps/dqlite/.libs/"
      LD_RUN_PATH: "/home/runner/go/deps/dqlite/.libs/"
      CGO_LDFLAGS_ALLOW: "(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Install build dependencies
        uses: $/.github/actions/install-lxd-builddeps

      - name: Build or restore dqlite/liblxc dependencies
        uses: $/.github/actions/cache-dqlite-liblxc
        with:
          export-env: true

      - name: Download go dependencies
        run: |
          set -eux
          go mod download
