name: Gentoo

on:
  schedule:
    - cron: '45 4 * * 1-5'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  # XXX: scheduled runs should not cancel manually triggered ones
  cancel-in-progress: ${{ !contains(github.event_name, 'schedule')}}

jobs:
  gentoo:
    if: github.event_name != 'schedule' || github.repository == 'canonical/lxd-ci'
    runs-on: ${{ matrix.architecture == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        release:
          - current  # EOL: never
        variant:
          - openrc
          - systemd
        architecture:
          - amd64
          - arm64
    env:
      type: "container"
      distro: "${{ github.job }}"
      target: "${HOME}/build"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/actions/image-setup

      - name: Determine image types
        env:
          ARCH: ${{ matrix.architecture }}
        run: |
          if [ "${ARCH}" = "amd64" ]; then
              echo "type=container,vm" >> $GITHUB_ENV
          fi

      - name: Build image
        env:
          ARCH: ${{ matrix.architecture }}
          DISTRO: ${{ env.distro }}
        run: |
          TIMEOUT=1800
          YAML="images/${DISTRO}.yaml"
          TYPE="${{ env.type }}"

          ./bin/build-distro "${YAML}" "${ARCH}" "${TYPE}" "${TIMEOUT}" "${{ env.target }}" \
              -o image.architecture="${ARCH}" \
              -o image.release=${{ matrix.release }} \
              -o image.variant=${{ matrix.variant }} \
              -o source.variant=${{ matrix.variant }}

      - name: Print build artifacts
        run: ls -lah "${{ env.target }}"

      - name: Test container image
        uses: ./.github/actions/image-test
        # avoid runaway test burning 6 hours of CI
        timeout-minutes: 20
        if: contains(env.type, 'container')
        with:
          type: container
          target: ${{ env.target }}
          distro: ${{ env.distro }}
          release: ${{ matrix.release }}
          variant: ${{ matrix.variant }}

      - name: Test VM image
        uses: ./.github/actions/image-test
        # avoid runaway test burning 6 hours of CI
        timeout-minutes: 40
        if: contains(env.type, 'vm')
        with:
          type: vm
          target: ${{ env.target }}
          distro: ${{ env.distro }}
          release: ${{ matrix.release }}
          variant: ${{ matrix.variant }}

      - name: Upload image
        uses: ./.github/actions/image-upload
        if: github.repository == 'canonical/lxd-ci'
        with:
          target: ${{ env.target }}
          image_dir: "${{ env.distro }}/${{ matrix.release }}/${{ matrix.architecture }}/${{ matrix.variant }}"
          ssh_private_key: "${{ secrets.LXD_INFRA_IMAGES_KEY }}" # zizmor: ignore[secrets-outside-env]
