name: Tests
on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'bin/**'
      - 'tests/**'
  schedule:
    - cron: '38 6 * * *'
  workflow_dispatch:
    inputs:
      ubuntu-releases:
        description: Ubuntu releases to run the tests against. In JSON format, i.e. '["22.04", "24.04", "26.04"]'.
        type: choice
        default: '["22.04", "24.04", "26.04"]'
        options:
          - '["22.04", "24.04", "26.04"]'
          - '["24.04", "26.04"]'
          - '["22.04", "24.04"]'
          - '["22.04"]'
          - '["24.04"]'
          - '["26.04"]'
      snap-track:
        description: Snap track to run the tests i.e. '["latest/edge", "5.0/candidate"]'.
        type: choice
        default: '["latest/edge"]'
        options:
          - '["latest/edge"]'
          - '["latest/candidate"]'
          - '["latest/stable"]'
          - '["6/edge"]'
          - '["6/candidate"]'
          - '["6/stable"]'
          - '["5.21/edge"]'
          - '["5.21/candidate"]'
          - '["5.21/stable"]'
          - '["5.0/edge"]'
          - '["5.0/candidate"]'
          - '["5.0/stable"]'
          - '["4.0/edge"]'
          - '["4.0/candidate"]'
          - '["4.0/stable"]'
      self-hosted-runner:
        type: boolean
        description: Whether to use self-hosted runners to run the jobs.
        default: false
      tmate-debug:
        description: Use tmate debugging session on integration test failure.
        type: boolean
        default: false
      tmate-timeout:
        description: Timeout in minutes to keep tmate debugging session.
        type: number
        default: 30

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ inputs.ubuntu-releases }}-${{ inputs.snap-track }}
  # XXX: scheduled runs should not cancel manually triggered ones
  cancel-in-progress: ${{ !contains(github.event_name, 'schedule')}}

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  code-tests:
    if: ${{ github.event_name != 'schedule' || github.repository == 'canonical/lxd-ci' }}
    name: Code
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # A non-shallow clone is needed for the Differential ShellCheck
          fetch-depth: 0
          persist-credentials: false

      - id: ShellCheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@d965e66ec0b3b2f821f75c8eff9b12442d9a7d1e # v5.5.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          strict-check-on-push: true
        if: github.event_name == 'pull_request'

      - name: Upload artifact with ShellCheck defects in SARIF format
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Differential ShellCheck SARIF
          path: ${{ steps.ShellCheck.outputs.sarif }}
        if: github.event_name == 'pull_request'

  system-tests:
    if: ${{ github.event_name != 'schedule' || github.repository == 'canonical/lxd-ci' }}
    name: ${{ matrix.test }} (${{ matrix.track }} - ${{ matrix.os }})
    runs-on: ubuntu-${{ matrix.os }}
    # avoid runaway test burning 6 hours of CI
    timeout-minutes: 60
    permissions:
      # need that to manipulate caches
      actions: write
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.ubuntu-releases || '["22.04", "24.04", "26.04"]') }}
        track: ${{ fromJSON(inputs.snap-track || '["6/edge", "5.21/edge", "5.0/edge"]') }}
        test:
          - cgroup
          - cloud-init
          - cluster
          - csi
          - container
          - container-copy
          - container-nesting
          - conversion
          - cpu-vm
          - devlxd
          - docker
          - efi-vm
          - lxd-installer
          - lxd-user
          - interception
          - network-bridge-firewall
          - network-ovn ovn:deb
          - network-ovn ovn:latest/edge
          - network-routed
          - pylxd
          - qemu-external-vm
          - snapcraft
          - snapd
          - storage-buckets
          - storage-disks-vm
          - storage-metadata
          - storage-vm btrfs
          - storage-vm ceph
          - storage-vm dir
          - storage-vm lvm
          - storage-vm lvm-thin
          - storage-vm zfs
          - storage-volumes-vm
          - tpm-vm
          - ui chromium
          - ui firefox
          - vm
          - vm-migration
          - vm-nesting
        exclude:
          - test: csi
            track: "4.0/candidate"
          - test: csi
            track: "4.0/edge"
          - test: csi
            track: "5.0/candidate"
          - test: csi
            track: "5.0/edge"
          - test: csi
            track: "5.21/stable"
          - test: csi
            track: "5.21/candidate"
          - test: csi
            track: "5.21/edge"
          - test: csi
            os: 22.04
          # not compatible with 4.0/*
          - test: cloud-init
            track: "4.0/candidate"
          - test: container-copy
            track: "4.0/candidate"
          - test: container-nesting
            track: "4.0/candidate"
          - test: conversion
            track: "4.0/candidate"
          - test: cpu-vm
            track: "4.0/candidate"
          - test: docker
            track: "4.0/edge"
          - test: docker
            track: "4.0/candidate"
          - test: lxd-installer
            track: "4.0/candidate"
          - test: lxd-user
            track: "4.0/candidate"
          - test: network-ovn ovn:deb
            track: "4.0/candidate"
          - test: network-ovn ovn:latest/edge
            track: "4.0/candidate"
          - test: qemu-external-vm
            track: "4.0/candidate"
          - test: snapcraft
            track: "4.0/candidate"
          - test: storage-buckets
            track: "4.0/candidate"
          - test: storage-disks-vm
            track: "4.0/candidate"
          - test: storage-metadata
            track: "4.0/candidate"
          - test: storage-vm btrfs
            track: "4.0/candidate"
          - test: storage-vm ceph
            track: "4.0/candidate"
          - test: storage-vm dir
            track: "4.0/candidate"
          - test: storage-vm lvm
            track: "4.0/candidate"
          - test: storage-vm lvm-thin
            track: "4.0/candidate"
          - test: storage-vm zfs
            track: "4.0/candidate"
          - test: storage-volumes-vm
            track: "4.0/candidate"
          - test: tpm-vm
            track: "4.0/candidate"
          - test: ui chromium
            track: "4.0/candidate"
          - test: ui firefox
            track: "4.0/candidate"
          - test: vm-migration
            track: "4.0/candidate"
          - test: cloud-init
            track: "4.0/edge"
          - test: container-copy
            track: "4.0/edge"
          - test: container-nesting
            track: "4.0/edge"
          - test: conversion
            track: "4.0/edge"
          - test: cpu-vm
            track: "4.0/edge"
          - test: lxd-installer
            track: "4.0/edge"
          - test: lxd-user
            track: "4.0/edge"
          - test: network-ovn ovn:deb
            track: "4.0/edge"
          - test: network-ovn ovn:latest/edge
            track: "4.0/edge"
          - test: qemu-external-vm
            track: "4.0/edge"
          - test: snapcraft
            track: "4.0/edge"
          - test: storage-buckets
            track: "4.0/edge"
          - test: storage-disks-vm
            track: "4.0/edge"
          - test: storage-metadata
            track: "4.0/edge"
          - test: storage-vm btrfs
            track: "4.0/edge"
          - test: storage-vm ceph
            track: "4.0/edge"
          - test: storage-vm dir
            track: "4.0/edge"
          - test: storage-vm lvm
            track: "4.0/edge"
          - test: storage-vm lvm-thin
            track: "4.0/edge"
          - test: storage-vm zfs
            track: "4.0/edge"
          - test: storage-volumes-vm
            track: "4.0/edge"
          - test: tpm-vm
            track: "4.0/edge"
          - test: ui chromium
            track: "4.0/edge"
          - test: ui firefox
            track: "4.0/edge"
          - test: vm-migration
            track: "4.0/edge"
          # not compatible with 5.0/*
          - test: cloud-init
            track: "5.0/candidate"
          - test: cloud-init
            track: "5.0/edge"
          - test: docker
            track: "5.0/edge"
          - test: docker
            track: "5.0/candidate"
          - test: lxd-installer
            track: "5.0/candidate"
          - test: lxd-installer
            track: "5.0/edge"
          - test: network-ovn ovn:latest/edge
            track: "5.0/candidate"
          - test: network-ovn ovn:latest/edge
            track: "5.0/edge"
          - test: qemu-external-vm
            track: "5.0/candidate"
          - test: qemu-external-vm
            track: "5.0/edge"
          - test: snapcraft
            track: "5.0/candidate"
          - test: snapcraft
            track: "5.0/edge"
          - test: vm-migration
            track: "5.0/candidate"
          - test: vm-migration
            track: "5.0/edge"
          # not compatible with 5.21/*
          - test: lxd-installer
            track: "5.21/stable"
          - test: lxd-installer
            track: "5.21/candidate"
          - test: lxd-installer
            track: "5.21/edge"
          - test: qemu-external-vm
            track: "5.21/stable"
          - test: qemu-external-vm
            track: "5.21/candidate"
          - test: qemu-external-vm
            track: "5.21/edge"
          - test: snapcraft
            track: "5.21/stable"
          - test: snapcraft
            track: "5.21/candidate"
          - test: snapcraft
            track: "5.21/edge"
          # some tests are not worth testing on specific OSes
          - os: 22.04
            test: lxd-installer
          - os: 22.04
            test: qemu-external-vm
          - os: 22.04
            test: snapcraft
          # skip track/os combinations that are too far appart
          - os: 24.04
            track: "4.0/candidate"
          - os: 24.04
            track: "4.0/edge"
          - os: 24.04
            track: "5.0/candidate"
          - os: 24.04
            track: "5.0/edge"
          - os: 26.04
            track: "4.0/candidate"
          - os: 26.04
            track: "4.0/edge"
          - os: 26.04
            track: "5.0/candidate"
          - os: 26.04
            track: "5.0/edge"

    steps:
      - name: Tune disk performance
        uses: canonical/lxd/.github/actions/tune-disk-performance@main # zizmor: ignore[unpinned-uses]

      - name: Reclaim some memory
        uses: canonical/lxd/.github/actions/reclaim-memory@main # zizmor: ignore[unpinned-uses]

      - name: Reclaim disk space
        # This can take multiple minutes if the runner is busy/slow so only run it when/where absolutely needed.
        if: ${{ matrix.test == 'conversion' || matrix.test == 'vm-nesting' || startsWith(matrix.test, 'storage-') }}
        uses: canonical/lxd/.github/actions/reclaim-disk-space@main # zizmor: ignore[unpinned-uses]

      - name: Disable Docker
        uses: canonical/lxd/.github/actions/disable-docker@main # zizmor: ignore[unpinned-uses]

      - name: "Disable br_netfilter"
        run: |
          set -eux
          # XXX: br_netfilter causes subtle issues by subjecting internal
          #      bridge traffic to NAT/MASQUERADING and IP filtering. This
          #      modules is not normally loaded on stock Ubuntu installs but it
          #      is on GHA runners.
          if lsmod | grep -qw ^br_netfilter; then
            sudo modprobe -r br_netfilter
          fi

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # needed for cache key
      - name: Get Date
        id: get-date
        if: ${{ matrix.test == 'qemu-external-vm' }}
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      # for simplicity, just use one cache directory
      # and make it valid for one day
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-restore
        if: ${{ matrix.test == 'qemu-external-vm' }}
        with:
          path: /home/runner/work/cache
          key: cache-${{ steps.get-date.outputs.date }}

      - name: Setup MicroCeph
        if: ${{ matrix.test == 'conversion' || matrix.test == 'storage-buckets' || matrix.test == 'storage-vm ceph' || matrix.test == 'storage-volumes-vm' || startsWith(matrix.test, 'ui ') }}
        uses: canonical/lxd/.github/actions/setup-microceph@main # zizmor: ignore[unpinned-uses]

      - name: Setup MicroOVN
        if: ${{ startsWith(matrix.test, 'ui ') }}
        uses: canonical/lxd/.github/actions/setup-microovn@main # zizmor: ignore[unpinned-uses]

      - name: CPU info
        run: lscpu

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        if: ${{ startswith(matrix.test, 'ui ') }}
        with:
          node-version: 22

      - name: Sanitize Artifact Name
        id: sanitize
        env:
          ID: ${{ matrix.test }}-${{ matrix.track }}
        run: |
          set -eux
          echo "artifact_name=$(echo "${ID}" | tr ': /' '-_-')" >> "${GITHUB_OUTPUT}"

      - name: ${{ matrix.test }} (${{ matrix.track }})
        run: |
          set -eux

          # Check if there are existing coredumps
          if [ -n "$(ls -A /var/crash/)" ]; then
            echo "WARNING: coredumps found before running the system tests, removing them"
            sudo rm /var/crash/*
          fi

          # XXX: prevent accidental usage of `images:` in CI test jobs.
          #      All tests should be done using officially supported images.
          echo '127.0.0.1 images.lxd.canonical.com' | sudo tee /etc/hosts

          TEST_SCRIPT="$(echo ${{ matrix.test }} | cut -d " " -f 1)"
          EXTRA_ARGS="$(echo ${{ matrix.test }} | cut -d " " -f 2- --only-delimited)"
          if [ "${TEST_SCRIPT}" = "cluster" ]; then
            dst_track="${MATRIX_TRACK}"
            src_track="$(echo "${dst_track}" | cut -d/ -f1)/stable"
            EXTRA_ARGS="${EXTRA_ARGS:-3} ${src_track} ${MATRIX_TRACK}"
          elif [ "${TEST_SCRIPT}" = "network-ovn" ]; then
            if [ -n "${EXTRA_ARGS}" ]; then
              # Strip the `ovn:` prefix
              export OVN_SOURCE="${EXTRA_ARGS##ovn:}"
              EXTRA_ARGS=""
            fi
          fi
          sudo --preserve-env=GITHUB_ACTIONS,GITHUB_STEP_SUMMARY,TEST_IMG,OVN_SOURCE ./bin/local-run "tests/${TEST_SCRIPT}" ${MATRIX_TRACK} ${EXTRA_ARGS:-}
        env:
          MATRIX_TRACK: ${{ matrix.track }}

      # always update cache as we have our own logic of
      # cache invalidation and updates in addition to a date check
      - name: Delete previous cache
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete "cache-${STEPS_GET_DATE_OUTPUTS_DATE}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STEPS_GET_DATE_OUTPUTS_DATE: ${{ steps.get-date.outputs.date }}
      - name: Set lxd channel env variable
        if: ${{ always() && startsWith(matrix.test, 'ui ') }}
        id: lxd-env
        run: |
          # need to change / to - in lxd channel string for report naming
          LXD_CHANNEL=$(echo ${MATRIX_TRACK} | sed 's#/#-#g')
          echo "LXD_CHANNEL=$LXD_CHANNEL" >> $GITHUB_OUTPUT
        env:
          MATRIX_TRACK: ${{ matrix.track }}
      - name: Upload ${{ matrix.test }}-${{ matrix.track }} test reports
        if: ${{ always() && startsWith(matrix.test, 'ui ') }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-report-${{ matrix.test }}-lxd-${{ steps.lxd-env.outputs.LXD_CHANNEL }}-os-${{ matrix.os }}
          path: lxd-ui/test-results
          retention-days: 1
      - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: ${{ matrix.test == 'qemu-external-vm' }}
        with:
          path: /home/runner/work/cache
          key: cache-${{ steps.get-date.outputs.date }}

      - name: Upload crash dumps
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: crash-dumps-${{ steps.sanitize.outputs.artifact_name }}
          path: |
            /var/crash/*
          retention-days: 5
          if-no-files-found: ignore

      - name: Tmate debugging session (self-hosted)
        if: ${{ failure() && inputs.tmate-debug && inputs.self-hosted-runner }}
        uses: canonical/action-tmate@5f11b26528699b78dadfb61273f4c859ac7145cf
        timeout-minutes: ${{ inputs.tmate-timeout }}
      - name: Tmate debugging session (gh-hosted)
        if: ${{ failure() && inputs.tmate-debug && !inputs.self-hosted-runner }}
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        timeout-minutes: ${{ inputs.tmate-timeout }}
