name: Tests
on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'snapcraft/**'
      - 'snapcraft.yaml'
      - 'lxd-snapcraft/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  code-tests:
    name: Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # A non-shallow clone is needed for the Differential ShellCheck
          fetch-depth: 0
          persist-credentials: false

      - id: ShellCheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@d965e66ec0b3b2f821f75c8eff9b12442d9a7d1e # v5.5.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'

      - name: Upload artifact with ShellCheck defects in SARIF format
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Differential ShellCheck SARIF
          path: ${{ steps.ShellCheck.outputs.sarif }}
        if: github.event_name == 'pull_request'

      - name: Run lxd-snapcraft unit tests
        working-directory: lxd-snapcraft
        run: go test -v ./...

      - name: Verify snap source-commits
        working-directory: lxd-snapcraft
        run: go run . -file ../snapcraft.yaml -verify-source-commits

  build:
    name: Test snap build
    needs: code-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # An official snap from the store is needed to allow `--dangerous` afterward
      # and LXD is needed to build the snap
      - name: Setup LXD
        uses: canonical/setup-lxd@a517a5346a08c624d81953578813a4fc0fe46e0b # main
        with:
          channel: >-
            ${{ fromJson('{
              "latest-edge": "latest/edge",
              "latest-candidate": "latest/candidate",
              "5.21-edge": "5.21/edge",
              "5.21-candidate": "5.21/candidate",
              "5.0-edge": "5.0/edge",
              "5.0-candidate": "5.0/candidate",
              "4.0-edge": "4.0/edge",
              "4.0-candidate": "4.0/candidate"
            }')[github.base_ref || github.ref_name] || 'latest/edge' }}

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1
        with:
          snapcraft-args: pack
          snapcraft-channel: latest/candidate

      - name: Upload snap artefact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lxd-snap
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
          retention-days: 1
          archive: false

      - name: Install freshly built snap
        run: |
          set -eux

          sudo snap install --dangerous lxd_*.snap
          sudo snap alias lxd.lxc lxc
          snap list --all

          lxc version

          echo "::group::LXD info"
          lxc info
          echo "::endgroup::"

      - name: Snap info
        run: |
          set -eux
          ls -lh lxd_*.snap
          cd /snap/lxd/current/
          du -smc *

          find | wc -l
          echo "::group::full-content"
          find
          echo "::endgroup::"

      - name: Smoke test
        run: |
          set -eux

          uname -a

          # Launch instances
          lxc launch ubuntu-minimal-daily:24.04 v1 --vm
          lxc launch ubuntu-minimal-daily:24.04 c1

          # Allow for boot to complete (PID > 0)
          { set +x; } 2>/dev/null
          echo -n "Waiting for instances to be ready"
          for _ in $(seq 120); do
            if [ "$(lxc list -f csv -c N | grep -cxE '[0-9]+')" -eq 2 ]; then
               echo "done"
               break
            fi
            echo -n .
            sleep 1
          done
          set -x

          # Quick tests
          lxc list
          lxc exec v1 -- hostname
          lxc exec c1 -- hostname

          # Cleanup
          lxc delete -f v1 c1
