name: Triaging
on:
  pull_request_target:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  label:
    if: github.event.pull_request
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    name: PR labels
    runs-on: ubuntu-slim
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
