name: GHA Security Analysis

on:
  push:
    branches:
      - main
      - stable-*
      - release-*
  pull_request:

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          # Use annotations on forks and advanced security features on the main repo.
          annotations: "${{ github.repository == 'canonical/lxd' && 'false' || 'true' }}"
          advanced-security: "${{ github.repository == 'canonical/lxd' && 'true' || 'false' }}"
